version: '3.7'
name: aws-offline
services:
  dynamodb:
    image: amazon/dynamodb-local
    container_name: dynamodb-offline
    hostname: dynamodb-offline
    # volumes:
    # - ./volume/data:/home/dynamodblocal/data
    ports:
      - 8000:8000
    command: [
        '-jar',
        'DynamoDBLocal.jar',
        '-sharedDb',
        '-inMemory',
        # '-dbPath',
        # '/home/dynamodblocal/data/',
      ]
